title:             Eureka
email:             brucelin1218@gmail.com
description:       Bruce Lin's Computer Science Learning Notes
author:            Bruce Lin
baseurl:           "/"
url:               "https://brucelin1218.github.io"

# Social Profiles
github_username:   brucelin1218

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
